### ISSUE TITLE
Rebrand

### ISSUE THREAD

**Issue by Serneum** [ElixirCLE/nermesterts#2]
CoverMyTabletop?
CoverMyGames?
Tabletop Roulette?

Give us options and vote

**Comment by mbramson** [comment]
Nermesterts

**Comment by joelbyler** [comment]
Can we call this done?

**Comment by Serneum** [comment]
I'd prefer to find a better name

**Comment by joelbyler** [comment]
Ok, but fwiw I originally didn't like nermesterts myself, and now its starting to grow on me :)
