### ISSUE TITLE
Store games in the database

### ISSUE THREAD

**Issue by Serneum** [ElixirCLE/nermesterts#3]
MVP:
- [x] Enter game name, min/max players in UI
- [x] Read games from the DB

Complete:
- [x] Add BGG game search
- [x] Pull game data from BGG

Optional:
- [x] Read from BGG collections

**Comment by Serneum** [comment]
MVP is done. See [this commit](https://github.com/ElixirCLE/nermesterts/commit/2b34ce3e2a0b6e81fab1b6f3151e5a589f47b7c9)

Sorry @mbramson, didn't see you assign this to yourself. Feel free to take over the BGG side of things

**Comment by mbramson** [comment]
Okay! Just going to submit some changes to seeds.exs to give us seed games to play around with. Am definitely going to dig deeper into BGG stuff tomorrow at some point.

**Comment by Serneum** [comment]
@daveshah said he played around with the BGG search API. He might have some pointers.

**Comment by Serneum** [comment]
This was completed in #52
